INSERT INTO college
VALUES
('University of Oklahoma'),
('University of Texas'),
('University of Oregon'),
('University of Cincinnati'),
('University of Louisville'),
('University of Utah'),
('University of Wyoming'),
('University of Houston'),
('University of Southern California'),
('Ohio State University'),
('Northwestern University'),
('Louisiana State University'),
('University of Arkansas'),
('Clemson University'),
('North Carolina State University'),
('Mississippi State University'),
('Central Michigan University'),
('Boise State University'),
('University of California'),
('Indiana University'),
('Utah State University'),
('Stanford University'),
('Texas A&M University'),
('Boston College'),
('University of Iowa'),
('Texas Tech University'),
('University of Michigan'),
('Fresno State'),
('Auburn University'),
('University of Missouri'),
('University of Georgia'),
('Wake Forest University'),
('University of Alabama'),
('Michigan State University'),
('University of Southern Mississippi'),
('Western Kentucky University'),
('Florida State University'),
('Texas Christian University'),
('Duke University'),
('Virginia Tech'),
('Brigham Young University'),
('Washington State University'),
('University of Pittsburgh'),
('University of North Carolina'),
('Eastern Illinois University'),
('Iowa State University'),
('North Dakota State University'),
('West Virginia University'),
('Liberty University'),
('Old Dominion University'),
('Temple University'),
('Purdue University'),
('Arizona State University'),
('University of South Carolina'),
('University of Virginia'),
('University of Minnesota'),
('University of Florida'),
('University of Central Florida'),
('University of Maryland'),
('University of Colorado'),
('Notre Dame University'),
('University of Arizona'),
('Tulane University'),
('Colorado State University'),
('Southern Methodist University'),
('Penn State University'),
('College of the Holy Cross'),
('University of Nevada'),
('University of Kentucky'),
('Oregon State University'),
('University of Washington'),
('University of Miami'),
('Malone University'),
('East Carolina University'),
('University of San Diego'),
('University of South Florida'),
('University of Pennsylvania'),
('Western Michigan University'),
('Kentucky Wesleyan College'),
('University of Tennessee'),
('California State University, Sacramento'),
('Eastern Washington University'),
('University of West Alabama'),
('Vanderbilt University'),
('Minnesota State University'),
('Baylor University'),
('Weber State University'),
('Middle Tennessee State University'),
('University of Mississippi'),
('University of Toledo'),
('University of Kansas'),
('Kansas State University'),
('Bowling Green State University'),
('Ball State University'),
('Oklahoma State University'),
('Florida Atlantic University'),
('University of Memphis'),
('Fordham University'),
('Kutztown University of Pennsylvania'),
('University of Texas at El Paso'),
('University of Wisconsin'),
('Illinois State University'),
('Rutgers University'),
('Georgia Southern University'),
('Western Colorado University'),
('University of North Texas'),
('South Dakota State University'),
('Louisiana Tech'),
('University of Louisiana'),
('Georgia Tech'),
('San Diego State University'),
('Arkansas State University'),
('Southern Illinois University'),
('Harvard University'),
('Coastal Carolina University'),
('San Jose State University'),
('Drake University'),
('Bryant University'),
('Indiana State University'),
('Virginia Commonwealth University'),
('University of Wisconsin-Platteville'),
('Valdosta State University'),
('University of South Alabama'),
('Stetson University'),
('University of Western Kentucky'),
('Florida International University'),
('University of Dayton'),
('University of Southern Arkansas'),
('University of Nebraska'),
('University of Massachusetts'),
('Appalachian State University'),
('University of Northern Iowa'),
('Southern Utah University'),
('Yale University'),
('Northern Illinois University'),
('Humboldt State University'),
('University of Illinois'),
('University of Tulsa'),
('Marshall University'),
('University of Wisconsin-Whitewater'),
('University at Buffalo'),
('University of California, Los Angeles'),
('Alabama State University'),
('Eastern Michigan University'),
('University of Sioux Falls'),
('Bloomsberg University of Pennsylvania'),
('Texas State University'),
('University of Arkansas at Pine Bluff'),
('Elon University'),
('University of Tennessee at Chattanooga'),
('Montana State University'),
('University of Connecticut'),
('None'),
('Grambling State University'),
('University of Idaho'),
('University of Texas at San Antonio'),
('James Madison University'),
('Rice University'),
('University of North Carolina at Charlotte'),
('Bucknell University'),
('Colorado State University Pueblo'),
('University of Alabama at Birmingham'),
('Lindenwood University'),
('University of Charleston'),
('Troy University'),
('Albany State University'),
('Missouri State University'),
('Western Illinois University'),
('Syracuse University'),
('University of Delaware'),
('Brown University'),
('Ferris State University'),
('Villanova University'),
('University of Manitoba'),
('Samford University'),
('Fort Hays State University'),
('Stephen F. Austin State University'),
('South Carolina State University'),
('University of Regina'),
('Miami University, Ohio'),
('Greenville University'),
('Wayne State University, Michigan'),
('Tarleton State University'),
('Houston Christian University'),
('University of South Dakota'),
('University of Hawaii'),
('Grand Valley State University'),
('Murray State University'),
('Pennsylvania Western University, California'),
('Southeast Missouri State University'),
('Tusculum University'),
('Jacksonville State University'),
('Washburn University'),
('University of Central Arkansas'),
('Pittsburg State University'),
('Ventura College'),
('Fayetteville State University'),
('Missouri Western State University'),
('Texas A&M University - Commerce'),
('Presbyterian College'),
('Western Carolina University'),
('Georgia State University'),
('Sam Houston State University'),
('Southern University'),
('College of William and Mary'),
('University of West Florida'),
('University of New Mexico'),
('Marist College');