INSERT INTO  state 
VALUES ('Arizona'),
    ('Georgia'),
    ('Maryland'),
    ('New York'),
    ('North Carolina'),
    ('Illinois'),
    ('Ohio'),
    ('Texas'),
    ('Colorado'),
    ('Michigan'),
    ('Wisconsin'),
    ('Indiana'),
    ('Florida'),
    ('Missouri'),
    ('Las Vegas'),
    ('California'),
    ('Minnesota'),
    ('Massachusetts'),
    ('Louisiana'),
    ('New Jersey'),
    ('Pennsylvania'),
    ('Washington'),
    ('Tennessee');